version: '3.4'

services:
  objective.api:
    image: ${DOCKER_REGISTRY-}objectiveapi
    build:
      context: .
      dockerfile: services/Objective/Objective.Api/Dockerfile

  webspa.server:
    image: ${DOCKER_REGISTRY-}webspaserver
    build:
      context: .
      dockerfile: clients/WebSpa/WebSpa.Server/Dockerfile
